// <auto-generated />
using System;
using GestionBornesCollecte.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionBornesCollecte.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260126153153_AddBenneMesureRelation")]
    partial class AddBenneMesureRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GestionBornesCollecte.Api.Models.Benne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapaciteMax")
                        .HasColumnType("int");

                    b.Property<string>("Localisation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Bennes");
                });

            modelBuilder.Entity("GestionBornesCollecte.Api.Models.Mesure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("BatterieVolt")
                        .HasColumnType("float");

                    b.Property<int>("BenneId")
                        .HasColumnType("int");

                    b.Property<int>("NiveauRemplissage")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BenneId");

                    b.ToTable("Mesures");
                });

            modelBuilder.Entity("GestionBornesCollecte.Api.Models.Mesure", b =>
                {
                    b.HasOne("GestionBornesCollecte.Api.Models.Benne", "Benne")
                        .WithMany("Mesures")
                        .HasForeignKey("BenneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Benne");
                });

            modelBuilder.Entity("GestionBornesCollecte.Api.Models.Benne", b =>
                {
                    b.Navigation("Mesures");
                });
#pragma warning restore 612, 618
        }
    }
}
